### ISSUE TITLE
Design website layout 

### ISSUE THREAD

**Issue by Spheroman** [Spheroman/ThingRanker#8]
Design a layout for each page, alongside a color palette and pick a font that fits it.

Preferably something modern and clean, with a mobile and desktop layout

Doesn't have to be an actual webpage but a drawing or a mockup to start, and then we can do the programming to make it work. 

Once this is finished, we can make the html. In the meantime, we can use just basic forms and tables.

We have 5 pages so far:
- index (homepage)
- landing (the tournament landing page)
- setup (see setup.php for more info)
- pairing (show 2 text options side to side with big buttons and maybe a submit option?)
- results (basically just a ranking table)

**Comment by Anzenith** [comment]
current work in progress figma file
https://www.figma.com/design/fkUNiNu0bEyCh0Jy0L1Cwo/ThingRanker?node-id=0%3A1&t=y7JFMhpbsLfxZt8D-1

**Comment by Spheroman** [comment]
It doesn't have to be food based, it's anything based. any sort of competition, not necessarily restaurants. That makes it more useful for general usage.

**Comment by Anzenith** [comment]
homepage, pairing, and results done in figma

**Comment by Anzenith** [comment]
Finished all the website design layouts
